const PREFIX = 'discs/';

export const GET_DISCS_REQUEST = `${PREFIX}GET_DISCS_REQUEST`;
export const GET_DISCS_SUCCESS = `${PREFIX}GET_DISCS_SUCCESS`;
export const GET_DISCS_ERROR = `${PREFIX}GET_DISCS_ERROR`;

export const SET_SELECTED_DISC = `${PREFIX}SET_SELECTED_DISC`;
